### ISSUE TITLE
Come to agreement on how non-live campaigns are displayed.

### ISSUE THREAD

**Issue by gaton2** [weifund/weifund-contracts#50]

**Comment by rverbee** [comment]
As a Campaigner on WeiFund, I want to be able to promote my campaign on WeiFund before it has gone live so that people can come and see where the campaign is and enter their email address into the mail chimp signup form. 

As a Contributor on Weifund, I want to be able to see campaigns that have not come live yet so that I can see upcoming campaigns and create reminders for myself to come back to WeiFund.

**Comment by rverbee** [comment]
This may be more complicated then we realize right now.

However, it seems that Nick is adding a "start date" to the campaign contracts.
That approach will make it difficult to update parameters of the contracts.
Of course, one way around that would be to just redeploy contracts and add the ability to update the registries. We should consider all of these points. In discussion and brainstorming.

**Comment by rverbee** [comment]
@SilentCicero @shahankhatch can we plan to finish to one this week. Perhaps have a conversation tomorrow afternoon in the office if that works for everyone?

**Comment by rverbee** [comment]
We have decided on the following based on @SilentCicero 's suggestions.

(1) We will handle non-live campaigns through a manual process at first that dos not scale. This will involve for Braid for instance putting their content into the front-end html code. We would then remove it once we deploy the campaign contracts (which don't have a start date attribute)

(2) To scale non-live campaigns, Nick has designed a "Start Campaign Contract" which basically is a placeholder for the campaign contract and has a start date. This contract system will have a Campaign Contract factory that can only be called when the start date has been passed.
